# Generated by Django 4.2 on 2023-06-18 14:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("object", django.db.models.manager.Manager()),],
        ),
    ]
