# Generated by Django 4.2.2 on 2023-10-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_id", models.IntegerField(blank=True, null=True)),
                ("thread_name", models.CharField(blank=True, max_length=20, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("message_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
